### ISSUE TITLE
2.2.1 Artifact Issue

### ISSUE THREAD

**Issue by henrydaly** [biscuit-auth/biscuit-java#51]
Hello, I see the latest version of `biscuit-java` is 2.2.1 in Github, but the public Maven repo (see [here](https://mvnrepository.com/artifact/com.clever-cloud/biscuit-java) and [here](https://repo1.maven.org/maven2/com/clever-cloud/biscuit-java/)) doesn't have this version available. Can someone push the artifact to Maven central when they get a chance?

**Comment by KannarFr** [comment]
Hello,

Due to the move of the repository from CleverCloud organization to biscuit-auth, the public repos are not allowing biscuit-auth publication. I bumped the subject on the matrix chat of biscuit.

I forked to the project under CleverCloud organization and ran the action to deploy the v2.2.1 artifact https://github.com/CleverCloud/biscuit-java/actions/runs/3823618060/jobs/6504974137. It succeeded, now we need to wait for the public repos batch, it should be ok by the end of the day.
